### PR TITLE
made app deal cards and fixed spelling error in deck

### PR DESCRIPTION
**Pull request by pauldalyiii**

### CODE REVIEW

**Review by AinzOowlGown44 — APPROVED** [review]

**Review by bloomkd46 — APPROVED** [review]
Looks good!

Output:
```
52 cards in this deck
0 cards in this deck
26 cards in first hand
26 cards in second hand
```

**Comment by E-tyedye22** [comment]
Approved

**Review by ManDownTheStreet — APPROVED** [review]
(in knuckles voice) Nice code, approved!

**Review by Brian-OOO — APPROVED** [review]

**Review by E-tyedye22 — APPROVED** [review]
You are smart

**Pull request merged**
